### ISSUE TITLE
Pythonでのif文

### ISSUE THREAD

**Issue by solitary-coffee** [fleneindre/lpgm-calculator#1]
日本語で失礼します
LPGMCalculator.pyの165 行目のIf分が気になりました、、

        if self.maxSva30 >= 100:
            self.LPGM = 4      
        elif self.maxSva30 >= 50:
                self.LPGM = 3
        elif self.maxSva30 >= 15:
                self.LPGM = 2
        elif self.maxSva30 >= 5:
                self.LPGM = 1
        else:
                self.LPGM = 0
        return self.LPGM
   
こちらのほうが正しい書き方だと思います、

**Comment by fleneindre** [comment]
提案ありがとうございます。 
ほとんどの場合、値は0であるため、チェックの順序を逆にしても含めました。

```
if self.maxSva30 < 5:
    self.LPGM = 0
elif self.maxSva30 < 15:
    self.LPGM = 1
elif self.maxSva30 < 50:
    self.LPGM = 2
elif self.maxSva30 < 100:
    self.LPGM = 3
else:
    self.LPGM = 4
return self.LPGM
```
